export enum Actions_Type {
   SET_TODOLISTS = 'SET-TODOLIST',
   ADD_TODOLIST = 'ADD-TODOLIST',
   REMOVE_TODOLIST = 'REMOVE-TODOLIST',
   CHANGE_TODOLIST_FILTER = 'CHANGE-TODOLIST-FILTER',
   CHANGE_TODOLIST_TITLE = 'CHANGE-TODOLIST-TITLE',

   ADD_TASK = 'ADD-TASK',
   REMOVE_TASK = 'REMOVE-TASK',
   CHANGE_TASK_STATUS = 'CHANGE-TASK-STATUS',
   CHANGE_TASK_TEXT = 'CHANGE-TASK-TEXT',
}
